# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Publish

on:
  push:
    branches: [ 'main' ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Print Version
        run: ./gradlew printVersion

      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./build/reports/jacoco
          flags: unittests
          verbose: true

      - name: Publish Snapshot to Maven Central
        if: startsWith(github.ref, 'refs/heads/')
        run: ./gradlew publishToSonatype
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}

      - name: Print Published Snapshot Version
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          VERSION=$(./gradlew printVersion -q)
          echo "✅ Successfully published snapshot version: $VERSION"
          echo "📦 Artifact: io.github.abaddon.kcqrs:kcqrs-EventStoreDB:$VERSION"
          echo "🔗 Repository: https://central.sonatype.com/repository/maven-snapshots/"
          echo ""
          echo "## 📦 Snapshot Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Artifact:** \`io.github.abaddon.kcqrs:kcqrs-EventStoreDB:$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** [Maven Central Snapshots](https://central.sonatype.com/repository/maven-snapshots/)" >> $GITHUB_STEP_SUMMARY

      - name: Publish Release to Maven Central
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_TOKEN: ${{ secrets.SONATYPE_TOKEN }}

      - name: Print Published Release Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=$(./gradlew printVersion -q)
          echo "✅ Successfully published release version: $VERSION"
          echo "📦 Artifact: io.github.abaddon.kcqrs:kcqrs-EventStoreDB:$VERSION"
          echo "🔗 Repository: https://repo.maven.apache.org/maven2/"
          echo ""
          echo "## 📦 Release Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Artifact:** \`io.github.abaddon.kcqrs:kcqrs-EventStoreDB:$VERSION\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** [Maven Central](https://repo.maven.apache.org/maven2/)" >> $GITHUB_STEP_SUMMARY
